### PR TITLE
Front end updates

### LINKED ISSUE #46: "About the project" text
Currently we have a placeholder with an "About the project" information, we need to eventually update it with actual text.

@KFArnold, when you have a draft of this text you can write it as a comment to this issue (but no pressure, i'm writing this issue to make sure we don't forget).

### LINKED ISSUE #118: Make KFArnold/covid-lockdown repo public and update source file locations

### LINKED ISSUE #119: Add Leeds and Turing logos to dashboard

### PR DESCRIPTION
**Pull request by crangelsmith**
Fixes #46 
Fixes #119 
Fixes #118

- [x] About the project info #46 
- [x] Add logos #119 
- [x] Update data links #118 
- [x] Centre the map better (at 50,0 lat long)

### CODE REVIEW

**Comment by crangelsmith** [comment]
This is how the landing page looks now.

Screenshot 2021-06-23 at 12 02 49

**Comment by crangelsmith** [comment]
About the project page:

Screenshot 2021-06-23 at 12 06 15

**Review by jemrobinson — APPROVED** [review]
Made some minor changes to remove hard-coded image sizes and ensure that elements were correctly centered.

**Comment by KFArnold** [comment]
Looks great! 😊

**Pull request merged**
